[window]
decorations = "none"
dynamic_padding = true
startup_mode = "SimpleFullscreen"
option_as_alt = "OnlyLeft"

[scrolling]
history = 100000

[font]
size = 16

[font.normal]
family = "Iosevka SS04"
style = "Regular"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  {action = "ToggleFullscreen", key = "Return", mods = "Super"},
  {action = "CreateNewWindow", key = "N", mods = "Super"},
  {action = "ClearHistory", key = "K", mods = "Super"}
]

# adapted from https://terminal.sexy/

[colors.primary]
#background = "0x1d1f21"
#foreground = "0xc5c8c6"
background = "0x1c1b1c"
foreground = "0xe8dbb6"

[colors.cursor]
#cursor = "0xc5c8c6"
#text = "0x1d1f21"
cursor = "0xc5c8c6"
text = "0x1d1f21"

[colors.normal]
black = "0x282a2e"
blue = "0x5f819d"
cyan = "0x5e8d87"
green = "0x8c9440"
magenta = "0x85678f"
red = "0xa54242"
white = "0x707880"
yellow = "0xde935f"

[colors.bright]
black = "0x373b41"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xc5c8c6"
yellow = "0xf0c674"
