#!/bin/sh

set -e

SESSION='chrometor'

# kill tor if already running (SIGHUP won't kill it)
pkill -x tor || true

# start with a fresh session
tmux kill-session -t "$SESSION" &>/dev/null || true

# tor pane
tmux new-session \
     -d \
     -s "$SESSION" \
     tor

# general purpose shell pane
tmux split-window \
     -t "$SESSION:1" \
     -h

# chrome pane
tmux split-window \
     -t "$SESSION:1.1" \
     -v \
     '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' \
     --user-data-dir=/tmp/cane \
     --no-first-run \
     --proxy-server=socks5://127.0.0.1:9050 \
     --incognito \
     --disable-gpu \
     https://check.torproject.org/

# switch to the shell
tmux select-pane \
     -t "$SESSION:1.3"

# switch to the session
tmux switch-client -t "$SESSION"
