#!/bin/sh

# fetch flags from chrome-launcher

flags=($(curl -s https://raw.githubusercontent.com/GoogleChrome/chrome-launcher/refs/heads/main/src/flags.ts \
             | sed 's/^export const DEFAULT_FLAGS: ReadonlyArray<string> = //;s/];/].map(x => console.log(x))/' \
             | node))

temp="$(mktemp -d)"
trap 'rm -fr $temp' EXIT

'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' \
    "${flags[@]}" \
    "--disable-gpu" \
    "--user-data-dir=$temp" \
    "--remote-debugging-port=9222" \
    "--headless" \
    "$@"
